[formatting]
line_length = 79

[language_servers.pylsp]
enable_ruff = true
enable_pyflakes = false
enable_flake8 = false
enable_pydocstyle = false
enable_mypy = true
enable_pylint = false
enabled = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[display]
dataframes = "rich"
theme = "dark"
code_editor_font_size = 14
default_width = "medium"
default_table_page_size = 10
default_table_max_columns = 50
reference_highlighting = false
cell_output = "below"

[package_management]
manager = "pip"

[snippets]
custom_paths = []
include_default_snippets = true

[mcp]
presets = []

[mcp.mcpServers]

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.models]
displayed_models = []
custom_models = []

[completion]
activate_on_typing = true
copilot = false

[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[experimental]

[runtime]
watcher_on_save = "lazy"
auto_instantiate = true
reactive_tests = true
auto_reload = "off"
default_auto_download = []
default_sql_output = "auto"
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
on_cell_change = "autorun"
